apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
spec:
  instances: {{ .Values.cluster.instances }}
  imageName: {{ .Values.cluster.imageName }}
  
  storage:
    size: {{ .Values.cluster.storageSize }}

  bootstrap:
    initdb:
      database: {{ .Values.credentials.database | quote }}
      owner: {{ .Values.credentials.username | quote }}
      secret:
        name: {{ .Values.cluster.name }}-creds