{{- range .Values.databases }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ .name }}
spec:
  cluster:
    name: {{ $.Values.cluster.name }}
  name: {{ .name }}
  owner: {{ .user }}
{{- end }}
